// Package customer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package customer

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field string `json:"field"`
	Issue string `json:"issue"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          string         `json:"code"`
	CorrelationId string         `json:"correlationId"`
	Details       *[]ErrorDetail `json:"details,omitempty"`
	Message       string         `json:"message"`
}

// RegisterCustomerRequest defines model for RegisterCustomerRequest.
type RegisterCustomerRequest struct {
	CorrelationId string              `json:"correlationId"`
	CustomerId    string              `json:"customerId"`
	Email         openapi_types.Email `json:"email"`
	HolderName    string              `json:"holderName"`
}

// RegisterCustomerResult defines model for RegisterCustomerResult.
type RegisterCustomerResult struct {
	CoreCustomerId string    `json:"coreCustomerId"`
	CustomerId     string    `json:"customerId"`
	RegisteredAt   time.Time `json:"registeredAt"`
	Status         string    `json:"status"`
}

// RegisterCustomerJSONRequestBody defines body for RegisterCustomer for application/json ContentType.
type RegisterCustomerJSONRequestBody = RegisterCustomerRequest
