// Package onboard provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package onboard

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OnboardRequestCardType.
const (
	AMEX       OnboardRequestCardType = "AMEX"
	MASTERCARD OnboardRequestCardType = "MASTERCARD"
	VISA       OnboardRequestCardType = "VISA"
)

// Valid indicates whether the value is a known member of the OnboardRequestCardType enum.
func (e OnboardRequestCardType) Valid() bool {
	switch e {
	case AMEX:
		return true
	case MASTERCARD:
		return true
	case VISA:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseAccountOnboardingStatus.
const (
	StatusResponseAccountOnboardingStatusFAILED     StatusResponseAccountOnboardingStatus = "FAILED"
	StatusResponseAccountOnboardingStatusINPROGRESS StatusResponseAccountOnboardingStatus = "IN_PROGRESS"
	StatusResponseAccountOnboardingStatusSUCCEEDED  StatusResponseAccountOnboardingStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the StatusResponseAccountOnboardingStatus enum.
func (e StatusResponseAccountOnboardingStatus) Valid() bool {
	switch e {
	case StatusResponseAccountOnboardingStatusFAILED:
		return true
	case StatusResponseAccountOnboardingStatusINPROGRESS:
		return true
	case StatusResponseAccountOnboardingStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseCustomerRegistrationStatus.
const (
	StatusResponseCustomerRegistrationStatusFAILED     StatusResponseCustomerRegistrationStatus = "FAILED"
	StatusResponseCustomerRegistrationStatusINPROGRESS StatusResponseCustomerRegistrationStatus = "IN_PROGRESS"
	StatusResponseCustomerRegistrationStatusSUCCEEDED  StatusResponseCustomerRegistrationStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the StatusResponseCustomerRegistrationStatus enum.
func (e StatusResponseCustomerRegistrationStatus) Valid() bool {
	switch e {
	case StatusResponseCustomerRegistrationStatusFAILED:
		return true
	case StatusResponseCustomerRegistrationStatusINPROGRESS:
		return true
	case StatusResponseCustomerRegistrationStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseInterestDetailsStatus.
const (
	StatusResponseInterestDetailsStatusFAILED     StatusResponseInterestDetailsStatus = "FAILED"
	StatusResponseInterestDetailsStatusINPROGRESS StatusResponseInterestDetailsStatus = "IN_PROGRESS"
	StatusResponseInterestDetailsStatusSUCCEEDED  StatusResponseInterestDetailsStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the StatusResponseInterestDetailsStatus enum.
func (e StatusResponseInterestDetailsStatus) Valid() bool {
	switch e {
	case StatusResponseInterestDetailsStatusFAILED:
		return true
	case StatusResponseInterestDetailsStatusINPROGRESS:
		return true
	case StatusResponseInterestDetailsStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseOverallStatus.
const (
	StatusResponseOverallStatusFAILED     StatusResponseOverallStatus = "FAILED"
	StatusResponseOverallStatusINPROGRESS StatusResponseOverallStatus = "IN_PROGRESS"
	StatusResponseOverallStatusSUCCEEDED  StatusResponseOverallStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the StatusResponseOverallStatus enum.
func (e StatusResponseOverallStatus) Valid() bool {
	switch e {
	case StatusResponseOverallStatusFAILED:
		return true
	case StatusResponseOverallStatusINPROGRESS:
		return true
	case StatusResponseOverallStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field string `json:"field"`
	Issue string `json:"issue"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          string         `json:"code"`
	CorrelationId string         `json:"correlationId"`
	Details       *[]ErrorDetail `json:"details,omitempty"`
	Message       string         `json:"message"`
}

// OnboardRequest defines model for OnboardRequest.
type OnboardRequest struct {
	CardNumber    string                 `json:"cardNumber"`
	CardType      OnboardRequestCardType `json:"cardType"`
	CorrelationId string                 `json:"correlationId"`
	CustomerId    string                 `json:"customerId"`
	Email         openapi_types.Email    `json:"email"`
	ExpiryDate    string                 `json:"expiryDate"`
	HolderName    string                 `json:"holderName"`
	JobId         string                 `json:"jobId"`
	RecordId      string                 `json:"recordId"`
	RowNumber     int                    `json:"rowNumber"`
	SourceFile    string                 `json:"sourceFile"`
}

// OnboardRequestCardType defines model for OnboardRequest.CardType.
type OnboardRequestCardType string

// OnboardResponse defines model for OnboardResponse.
type OnboardResponse struct {
	AccountId      string `json:"accountId"`
	CardId         string `json:"cardId"`
	CoreCustomerId string `json:"coreCustomerId"`
	CustomerId     string `json:"customerId"`
	Status         string `json:"status"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	AccountOnboardingMessage    *string                                   `json:"accountOnboardingMessage,omitempty"`
	AccountOnboardingStatus     *StatusResponseAccountOnboardingStatus    `json:"accountOnboardingStatus,omitempty"`
	CustomerId                  string                                    `json:"customerId"`
	CustomerRegistrationMessage *string                                   `json:"customerRegistrationMessage,omitempty"`
	CustomerRegistrationStatus  *StatusResponseCustomerRegistrationStatus `json:"customerRegistrationStatus,omitempty"`
	InterestDetailsMessage      *string                                   `json:"interestDetailsMessage,omitempty"`
	InterestDetailsStatus       *StatusResponseInterestDetailsStatus      `json:"interestDetailsStatus,omitempty"`
	OverallStatus               StatusResponseOverallStatus               `json:"overallStatus"`
}

// StatusResponseAccountOnboardingStatus defines model for StatusResponse.AccountOnboardingStatus.
type StatusResponseAccountOnboardingStatus string

// StatusResponseCustomerRegistrationStatus defines model for StatusResponse.CustomerRegistrationStatus.
type StatusResponseCustomerRegistrationStatus string

// StatusResponseInterestDetailsStatus defines model for StatusResponse.InterestDetailsStatus.
type StatusResponseInterestDetailsStatus string

// StatusResponseOverallStatus defines model for StatusResponse.OverallStatus.
type StatusResponseOverallStatus string

// OnboardCardJSONRequestBody defines body for OnboardCard for application/json ContentType.
type OnboardCardJSONRequestBody = OnboardRequest
