// Package account provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package account

// Defines values for InterestDetailsResponseInterestType.
const (
	FIXED    InterestDetailsResponseInterestType = "FIXED"
	VARIABLE InterestDetailsResponseInterestType = "VARIABLE"
)

// Valid indicates whether the value is a known member of the InterestDetailsResponseInterestType enum.
func (e InterestDetailsResponseInterestType) Valid() bool {
	switch e {
	case FIXED:
		return true
	case VARIABLE:
		return true
	default:
		return false
	}
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field string `json:"field"`
	Issue string `json:"issue"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          string         `json:"code"`
	CorrelationId string         `json:"correlationId"`
	Details       *[]ErrorDetail `json:"details,omitempty"`
	Message       string         `json:"message"`
}

// InterestDetailsResponse defines model for InterestDetailsResponse.
type InterestDetailsResponse struct {
	Currency     string                              `json:"currency"`
	CustomerId   string                              `json:"customerId"`
	InterestRate float32                             `json:"interestRate"`
	InterestType InterestDetailsResponseInterestType `json:"interestType"`
	ProductCode  string                              `json:"productCode"`
}

// InterestDetailsResponseInterestType defines model for InterestDetailsResponse.InterestType.
type InterestDetailsResponseInterestType string
